### ISSUE TITLE
unity2018.3.5用il2cpp打包报错

### ISSUE THREAD

**Issue by ddy2015** [CatLib/CatLib.ILRuntime#7]
IL2CPP error for method 'ILRuntime.Runtime.Stack.StackObject* ILRuntime.Runtime.Generated.CatLib_App_Binding::BindIf_30(ILRuntime.Runtime.Intepreter.ILIntepreter,ILRuntime.Runtime.Stack.StackObject*,System.Collections.Generic.IList`1<System.Object>,ILRuntime.CLR.Method.CLRMethod,System.Boolean)' in assembly '/Users/mgnddymac/WorkDDY/UnityProject/demo-how-to-use-catlib-for-ilruntime-master/Temp/StagingArea/Data/Managed/CatLib.ILRuntime.dll'
Additional information: Build a development build for more information. Exception of type 'System.Exception' was thrown.

Failed running /Applications/Unity/Unity.app/Contents/il2cpp/build/il2cppcore/il2cppcore.dll --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --map-file-parser="/Applications/Unity/Unity.app/Contents/Tools/MapFileParser/MapFileParser" --directory="/Users/mgnddymac/WorkDDY/UnityProject/demo-how-to-use-catlib-for-ilruntime-master/Temp/StagingArea/Data/Managed" --generatedcppdir="/Users/mgnddymac/WorkDDY/UnityProject/demo-how-to-use-catlib-for-ilruntime-master/Temp/il2cppOutput/il2cppOutput" 

stdout:
IL2CPP error for method 'ILRuntime.Runtime.Stack.StackObject* ILRuntime.Runtime.Generated.CatLib_App_Binding::BindIf_30(ILRuntime.Runtime.Intepreter.ILIntepreter,ILRuntime.Runtime.Stack.StackObject*,System.Collections.Generic.IList`1<System.Object>,ILRuntime.CLR.Method.CLRMethod,System.Boolean)' in assembly '/Users/mgnddymac/WorkDDY/UnityProject/demo-how-to-use-catlib-for-ilruntime-master/Temp/StagingArea/Data/Managed/CatLib.ILRuntime.dll'
Additional information: Build a development build for more information. Exception of type 'System.Exception' was thrown.
il2cpp.exe didn't catch exception: System.Exception: Exception of type 'System.Exception' was thrown.
   at Unity.IL2CPP.MethodBodyWriter.GetPointerOrByRefType(StackInfo address)
   at Unity.IL2CPP.MethodBodyWriter.LoadIndirectNativeInteger()
   at Unity.IL2CPP.MethodBodyWriter.ProcessInstruction(Node node, InstructionBlock block, Instruction& ins)
   at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive(Node node)
   at Unity.IL2CPP.MethodBodyWriter.Generate()
   at Unity.IL2CPP.CodeWriterExtensions.WriteMethodWithMetadataInitialization(IGeneratedMethodCodeWriter writer, String methodSignature, String methodFullName, Action`2 writeMethodBody, String uniqueIdentifier, MethodReference methodRef)
   at Unity.IL2CPP.MethodWriter.WriteMethodDefinition(IGeneratedMethodCodeWriter writer, MethodReference method, IMethodCollector methodCollector, IMethodVerifier methodVerifier, ISourceAnnotationWriter sourceAnnotationWriter, IIcallMappingService icallMapping, VTableBuilder vtableBuilder)
   at Unity.IL2CPP.SourceWriter.<>c__DisplayClass12_0.<WriteMethodSourceFiles>b__0(IGeneratedMethodCodeWriter writer, TypeReference type)
   at Unity.IL2CPP.SourceWriter.WriteEqualSizedChunks[T](NPath outputDir, IEnumerable`1 items, String fileName, Int64 chunkSize, Action`2 writeItemAction, SourceWritingContext sourceWritingContext)
   at Unity.IL2CPP.SourceWriter.WriteMethodSourceFiles(NPath outputDirectory, SourceWritingContext sourceWritingContext, String fileName, IEnumerable`1 typeList, IMethodCollector methodCollector, Boolean writeMarshalingDefinitions)
   at Unity.IL2CPP.SourceWriter.Write(NPath outputDir, SourceWritingContext sourceWritingContext, ReadOnlyCollection`1 assemblyDefinitions, IMethodCollector methodCollector, IInteropDataCollector interopDataCollector)
   at Unity.IL2CPP.AssemblyConverter.Apply()
   at Unity.IL2CPP.AssemblyConverter.ConvertAssemblies(IEnumerable`1 assemblyDirectories, IEnumerable`1 explicitAssemblies, NPath outputDir, NPath dataFolder, NPath symbolsFolder, NPath executableAssembiesFolder, NPath monoLibFolder, NPath monoEtcFolder, NPath[] searchDirectories, String entryAssemblyName, NPath[] extraTypesFiles)
   at il2cpp.Program.DoRun(String[] args)
   at il2cpp.Program.Run(String[] args)
   at il2cpp.Program.Main(String[] args)
stderr:

Unhandled Exception: System.Exception: Exception of type 'System.Exception' was thrown.
   at Unity.IL2CPP.MethodBodyWriter.GetPointerOrByRefType(StackInfo address)
   at Unity.IL2CPP.MethodBodyWriter.LoadIndirectNativeInteger()
   at Unity.IL2CPP.MethodBodyWriter.ProcessInstruction(Node node, InstructionBlock block, Instruction& ins)
   at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive(Node node)
   at Unity.IL2CPP.MethodBodyWriter.Generate()
   at Unity.IL2CPP.CodeWriterExtensions.WriteMethodWithMetadataInitialization(IGeneratedMethodCodeWriter writer, String methodSignature, String methodFullName, Action`2 writeMethodBody, String uniqueIdentifier, MethodReference methodRef)
   at Unity.IL2CPP.MethodWriter.WriteMethodDefinition(IGeneratedMethodCodeWriter writer, MethodReference method, IMethodCollector methodCollector, IMethodVerifier methodVerifier, ISourceAnnotationWriter sourceAnnotationWriter, IIcallMappingService icallMapping, VTableBuilder vtableBuilder)
   at Unity.IL2CPP.SourceWriter.<>c__DisplayClass12_0.<WriteMethodSourceFiles>b__0(IGeneratedMethodCodeWriter writer, TypeReference type)
   at Unity.IL2CPP.SourceWriter.WriteEqualSizedChunks[T](NPath outputDir, IEnumerable`1 items, String fileName, Int64 chunkSize, Action`2 writeItemAction, SourceWritingContext sourceWritingContext)
   at Unity.IL2CPP.SourceWriter.WriteMethodSourceFiles(NPath outputDirectory, SourceWritingContext sourceWritingContext, String fileName, IEnumerable`1 typeList, IMethodCollector methodCollector, Boolean writeMarshalingDefinitions)
   at Unity.IL2CPP.SourceWriter.Write(NPath outputDir, SourceWritingContext sourceWritingContext, ReadOnlyCollection`1 assemblyDefinitions, IMethodCollector methodCollector, IInteropDataCollector interopDataCollector)
   at Unity.IL2CPP.AssemblyConverter.Apply()
   at Unity.IL2CPP.AssemblyConverter.ConvertAssemblies(IEnumerable`1 assemblyDirectories, IEnumerable`1 explicitAssemblies, NPath outputDir, NPath dataFolder, NPath symbolsFolder, NPath executableAssembiesFolder, NPath monoLibFolder, NPath monoEtcFolder, NPath[] searchDirectories, String entryAssemblyName, NPath[] extraTypesFiles)
   at il2cpp.Program.DoRun(String[] args)
   at il2cpp.Program.Run(String[] args)
   at il2cpp.Program.Main(String[] args)
   at Program.Main(String[] args)

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunProgram(Program, String, String, String, CompilerOutputParserBase) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:128)
UnityEditorInternal.Runner:RunNetCoreProgram(String, String, String, CompilerOutputParserBase, Action`1) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:79)
UnityEditorInternal.IL2CPPBuilder:RunIl2CppWithArguments(List`1, Action`1, String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:366)
UnityEditorInternal.IL2CPPBuilder:ConvertPlayerDlltoCpp(String, String, String, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:349)
UnityEditorInternal.IL2CPPBuilder:Run() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:211)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:35)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by ddy2015** [comment]
demo地址https://github.com/ddy2015/how-to-use-catlib-for-ilruntime-ddydemo.git

**Comment by yb199478** [comment]
感谢上报异常，目前在我们这复现出了同样的错误，正在定位错误原因。

**Comment by yb199478** [comment]
从目前已有的信息看来，这应该是一个IL2CPP的Bug，我们正在联系插件提供商来处理这个问题。

**Comment by ddy2015** [comment]
@yb199478 感谢反馈，不知道您是否了解这个bug在unity有没有Issue ID，我可以追踪下。我会先在自己的项目中想办法规避这个问题。

**Comment by ddy2015** [comment]
我实测unity2018.2.20和unity2018.3.9已经没有问题了

**Comment by yb199478** [comment]
Unity官方的Issues Track中提到了类似bug导致的异常：

https://issuetracker.unity3d.com/issues/il2cpp-error-for-type-system-dot-array-in-assembly-mscorlib-dot-dll-when-building-to-ios

目前建议通过升级Unity次要版本的方式来修复这个问题。
